# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Observability for AI Coding Assistants"
  homepage "https://intentra.sh"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.7.0/intentra_0.7.0_darwin_amd64.tar.gz"
      sha256 "45e8719e859f01532c718a1c91b308eed79058d22802bf1cb7af8977c1e31dea"

      def install
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.7.0/intentra_0.7.0_darwin_arm64.tar.gz"
      sha256 "2459fda9f14f948f91f295011e0968e1ada9bb6fb31579c3a2031d59d15537ae"

      def install
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.7.0/intentra_0.7.0_linux_amd64.tar.gz"
      sha256 "b52999bd0bd827a7bb552a1b2cd82752972b36f8da031ee6e3c1cd0ab355c542"
      def install
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.7.0/intentra_0.7.0_linux_arm64.tar.gz"
      sha256 "534b0db68ca47af4f25554674bef3f27e3043481d1a20efdb52e3e0ebda01d0f"
      def install
        bin.install "intentra"
      end
    end
  end

  test do
    system "#{bin}/intentra", "--version"
  end
end
