# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Observability for AI Coding Assistants"
  homepage "https://intentra.sh"
  version "0.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.9.1/intentra_0.9.1_darwin_amd64.tar.gz"
      sha256 "79d4544c04b7c93ec47a6463c7d80625aa12eef2bc6bac0a62f890c5f092def7"

      def install
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.9.1/intentra_0.9.1_darwin_arm64.tar.gz"
      sha256 "dc4cf7008f6a85513114d5081908e1bcd9cd62281c2a057c570c6bc58492c5f5"

      def install
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.9.1/intentra_0.9.1_linux_amd64.tar.gz"
      sha256 "26790b7ba822c07afe8f643e3f1d8d7857529f0d57be12157f15480100f9b6a7"
      def install
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atbabers/intentra-cli/releases/download/v0.9.1/intentra_0.9.1_linux_arm64.tar.gz"
      sha256 "f4dff3eee333720dce510d88a88e905bcf96d19670f82258c9ba9e1c3157cafa"
      def install
        bin.install "intentra"
      end
    end
  end

  test do
    system "#{bin}/intentra", "--version"
  end
end
